### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by Rad586**

### CODE REVIEW

**Comment by Sweenus** [comment]
Thank you for your work! 🙂

**Comment by avirtual777** [comment]
Do you really think 钗 is a kind of weapon?

**Comment by Rad586** [comment]
> Do you really think 钗 is a kind of weapon?

钗 itself doesn't mean weapon, it's used to transliterate "sai". If you search "sai" + "weapon", you'll found it translated as 钗 everywhere. It's a common sense that 钗 means sai, then there's no need to add a qualifier.

**Comment by avirtual777** [comment]
> > Do you really think 钗 is a kind of weapon?
> 
> 钗 itself doesn't mean weapon, it's used to transliterate "sai". If you search "sai" + "weapon", you'll found it translated as 钗 everywhere. It's a common sense that 钗 means sai, then there's no need to add a qualifier.

Apparently 钗 will confuse most zh-CN readers at the very first sight, which is the most important. So it is not a perfect translation.
Sai is a Japanese word, and according to my search result, it develops from 铁尺, which also named 笔架叉. I suppose 笔架叉 is a much better translation.
SInce there are some more things need to improve on the unique weapons, I'll send my own PR later after I finish the work of the Pachouli book.

**Comment by Rad586** [comment]
> > > Do you really think 钗 is a kind of weapon?
> > 
> > 
> > 钗 itself doesn't mean weapon, it's used to transliterate "sai". If you search "sai" + "weapon", you'll found it translated as 钗 everywhere. It's a common sense that 钗 means sai, then there's no need to add a qualifier.
> 
> Apparently 钗 will confuse most zh-CN readers at the very first sight, which is the most important. So it is not a perfect translation. Sai is a Japanese word, and according to my search result, it develops from 铁尺, which also named 笔架叉. I suppose 笔架叉 is a much better translation. SInce there are some more things need to improve on the unique weapons, I'll send my own PR later after I finish the work of the Pachouli book.

Oops, I made it backwards, sai is used to transliterate 钗. 
When it comes to common sense, 钗(lit. 'hairpin') is quite acceptable, since there‘s 钗 already in CODM. 
铁尺(lit. 'iron ruler') is better known than 笔架叉(lit. 'penholder'), but only for those who knows well about weapons. 
For easier understanding, 三叉刺(lit. 'tri-stabber') should be clear enough, since it not only describes its shape(like trident), but also shows its main usage(stabbing).

**Pull request merged**
