### PR TITLE
Clean up unique weapons code, fix lichblade behavior

### PR DESCRIPTION
**Pull request by KreloX**
Clean up all unique weapon classes (redundant checks and formatting)

Fix a few weird tooltips

Fix lichblades' abilities according to their description in en_us.json

### CODE REVIEW

**Review by Sweenus — APPROVED** [review]
Thank you!!

**Comment by Sweenus** [comment]
@KreloX Do you have a CurseForge account I can add as a contributor to the modpage?

**Comment by Sweenus** [comment]
Also, just FYI. Lichblade does not quite behave correctly with these changes. The souls should physically path back to the player towards the end of the ability usage. All other weapons appear to be working perfectly 👍

**Comment by KreloX** [comment]
Sorry about that, is this about the waking lichblade where it just blinks back, or is there a problem with the awakened one as well (like after the enemy is dead should they return even without the player holding right-click)? 

And my curseforge account is [kreloxcz](https://legacy.curseforge.com/members/kreloxcz/projects)

**Comment by Sweenus** [comment]
No worries!
Actually, on closer inspection - the way you've done it is great. It returns to you after the enemy dies. I didn't notice this at first because I usually test on unkillable dummies.

When used on an unkillable target it never returns to the player, nor does it trigger the item cooldown. Allowing you to use it indefinitely if the target doesn't die and you maintain the cast. It may also need to return to the player after a certain duration of ticks passes, or at least trigger the cooldown if the target does not die. (I can fix this myself if you don't have the time 🙂 )

**Pull request merged**
