### PR TITLE
Added Japanese translation

### PR DESCRIPTION
**Pull request by SAGA23456**

### CODE REVIEW

**Comment by Sweenus** [comment]
Hi there 👋 

Thank you for your contribution!
Please know, however, that this is an old branch that is unlikely to see updates.
Architectury-1.20 is the latest branch - I've updated this to be the default.

**Comment by SAGA23456** [comment]
I will also add it to Architecture-1.20.

**Comment by SAGA23456** [comment]
I will rebuild to Architecture-1.20.

**Comment by SAGA23456** [comment]
I will rebuild to Architecture-1.20.

**Pull request closed without merging**
