### PR TITLE
Add maximum duration to lichblade's ability

### PR DESCRIPTION
**Pull request by KreloX**
Add maximum duration to lichblade's ability, config dependent -> change default value of soulAnguishDuration from 500f to 200f

Remove redundant checks in AbilityMethods class

### CODE REVIEW

**Comment by KreloX** [comment]
I also removed some unused (or used in a way that didn't do anything) parameters from the tickAbilitySoulAnguish method and coresponding unused variables in the LichbladeSwordItem class. If they are needed in the future it would be better to just add local variables.

**Review by Sweenus — APPROVED** [review]
Thank you!
As you've no doubt noticed, I have a bad habit of leaving behind redundant checks and unused variables 🤦‍♂️
Glad to have it all cleaned up 🙂

**Comment by Sweenus** [comment]
That revised Lichblade behaviour is absolutely perfect, by the way!

**Comment by KreloX** [comment]
Should I replace the 30 second absorption effect with just giving the player absorption hearts equal to the damage they dealt by the souls?

Also I looked at the omen effect, it says it gives absorption but it looks like that was later changed to regeneration. Should I make it so that it gives absorption hearts equal to the enemy's remaining health? 
edit: Actually it says a portion of the enemy health, so if I should make it that way, then tell me how big should the portion be or if it should be config dependent, then a default value would be needed. I think it would be best to give the player all of the remaining health but set a cap, which would be configurable and the default value would be 20 for one full row of absorption hearts.

**Comment by Sweenus** [comment]
So, I've been steering away from absorption more recently, due to balance issues. This is why you might see references to Absorption when the effect has actually been replaced with Regeneration.
The primary issue is that someone can load up on Absorption from a weapon effect and then eat Golden Apples to greatly extend the duration.

I need to redesign these weapon effects at some point, and so my temporary solution has just been to grant regeneration instead.

**Pull request merged**
