### PR TITLE
zh_cn translations update

### PR DESCRIPTION
**Pull request by avirtual777**
The right branch here :)
Modified some translations and names
Also with a Chinese Pachouli book :)

### CODE REVIEW

**Comment by Rad586** [comment]
Added translations for new weapons: 
https://gist.github.com/Rad586/27a6b4460d0704c8028fe38a32291d5d

**Comment by avirtual777** [comment]
> Added translations for new weapons: https://gist.github.com/Rad586/27a6b4460d0704c8028fe38a32291d5d

Thx. Updated.

**Comment by Sweenus** [comment]
Amazing work. Thank you both! 🙂

**Comment by JerryWn12** [comment]
Thanks for your translation! The translation update is strongly needed and if you could publish a new release for it? @Sweenus

**Pull request merged**
